project:
  type: website
  output-dir: docs

website:
  title: "MaxEnt"
  navbar:
    left:
      - href: quarto/index.qmd
        text: Home

format:
  html:
    theme: darkly
    css: quarto/styles.css
    toc: true
    include-in-header:
      - text: |
          <meta name="robots" content="noindex">

execute: 
  freeze: auto

