project:
  type: website
  output-dir: docs

website:
  title: "MaxEnt"
  navbar:
    left:
      - href: quarto/index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: quarto/styles.css
    toc: true

execute: 
  freeze: auto

