name = "KLLS"
uuid = "a1edf54d-33cf-4bd3-8f57-70bdaf668f08"
authors = ["Michael Friedlander <michael@friedlander.io> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
